export const artWorkList = [
    {name: 'women_in_black', img:'/artWorks/women_in_black.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'vagabond', img:'/artWorks/vagabond.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'toph', img:'/artWorks/toph.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'the_night', img:'/artWorks/the_night.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'still_apple', img:'/artWorks/still_apple.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'Steven-moonknight', img:'/artWorks/Steven-moonknight.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'sraw', img:'/artWorks/sraw.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'spot', img:'/artWorks/spot.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'snowy-tundra', img:'/artWorks/snowy-tundra.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'skull', img:'/artWorks/skull.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'raven', img:'/artWorks/raven.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'praticeduh', img:'/artWorks/praticeduh.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'orangelightlady', img:'/artWorks/orangelightlady.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'neon_chubby', img:'/artWorks/neon_chubby.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'monkeyking', img:'/artWorks/monkeyking.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'left_the_gas_on', img:'/artWorks/left_the_gas_on.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'KRISHNA', img:'/artWorks/KRISHNA.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'hunter', img:'/artWorks/hunter.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'hf-2', img:'/artWorks/hf-2.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'hf-1', img:'/artWorks/hf-1.jpg' ,artist: 'Jayesh Samlu', year: 1503},
    {name: 'hand1', img:'/artWorks/hand1.jpg' ,artist: 'Jayesh Samlu', year: 1503},

];